apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "library.metadata.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ include "library.service.auth" . }}
    nginx.ingress.kubernetes.io/auth-signin: /login
spec:
  rules:
    - host: {{ include "library.ingress.host" . }}
      http:
        paths:
          - path: /container-file-manager
            pathType: Prefix
            backend:
              service:
                name: {{ include "library.metadata.name" . }}
                port:
                  number: {{ include "library.service.port" . }}
