repos:
  - repo: local
    hooks:
      - id: "pnpm-pre-commit"
        name: "pnpm pre-commit"
        language: "system"
        entry: "pnpm run pre-commit"
        pass_filenames: false
        files: \.(js|jsx|ts|tsx)$
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        language_version: 14.13.0
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
