{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
            type: Directory
      containers:
      - name: update-server
        image: orchest/update-server:latest
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 80        
        env:
        - name: "ORCHEST_PORT"
          value: "8000"
        - name: "USERDIR_PVC"
          value: "userdir-pvc"
        - name: "HOST_CONFIG_DIR"
          value: "config_pvc"
        - name: "HOST_REPO_DIR"
          value: "/var/lib/orchest/repo"
        - name: "HOST_OS"
          value: "linux"
        volumeMounts:
         - name: dockersock
           mountPath: /var/run