apiVersion: v2
description: The helm chart for update-sidecar service
name: update-sidecar
version: "0.0.1"
icon: https://github.com/orchest/orchest/blob/master/docs/source/img/logo.png
sources:
  - https://github.com/orchest/orchest
