name: Docker CI

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the master branch. NOTE: if you
# change event types make sure you are not breaking the
# dispatch-version-update-info job.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  buildpush:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    strategy:
      matrix:
        image:
          [
            -i orchest-api,
            -i orchest-webserver,
            -i auth-server,
            -i jupyter-server,
            -i jupyter-enterprise-gateway,
            -i base-kernel-py,
            -i base-kernel-r,
            -i base-kernel-julia,
            -i base-kernel-javascript,
            -i node-agent,
            -i orchest-controller,
            -i celery-worker,
            -i session-sidecar,
            -i image-puller,
            -i image-builder-buildx,
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Build and push image
        run: |
          bash ./scripts/build_container.sh ${{ matrix.image }} \
                    -o ${GITHUB_REF#refs/tags/} \
                    -t ${GITHUB_REF#refs/tags/} \
                    -v
          echo "-----------"
          bash ./scripts/push_container.sh ${{ matrix.image }} -t ${GITHUB_REF#refs/tags/}

  push-readme:
    needs: buildpush
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Push README files to DockerHub celery-worker
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/celery-worker
          README_FILEPATH: services/orchest-api/README.md

      - name: Push README files to DockerHub base-kernel-r
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-r
          README_FILEPATH: services/base-images/base-kernel-r/README.md

      - name: Push README files to DockerHub base-kernel-julia
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-julia
          README_FILEPATH: services/base-images/base-kernel-julia/README.md

      - name: Push README files to DockerHub base-kernel-javascript
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-javascript
          README_FILEPATH: services/base-images/base-kernel-javascript/README.md

      - name: Push README files to DockerHub base-kernel-py
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-py
          README_FILEPATH: services/base-images/base-kernel-py/README.md

      - name: Push README files to DockerHub orchest-api
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/orchest-api
          README_FILEPATH: services/orchest-api/README.md

      - name: Push README files to DockerHub jupyter-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/jupyter-server
          README_FILEPATH: services/jupyter-server/README.md

      - name: Push README files to DockerHub jupyter-enterprise-gateway
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/jupyter-enterprise-gateway
          README_FILEPATH: services/jupyter-enterprise-gateway/README.md

      - name: Push README files to DockerHub orchest-webserver
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/orchest-webserver
          README_FILEPATH: services/orchest-webserver/README.md

      - name: Push README files to DockerHub auth-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/auth-server
          README_FILEPATH: services/auth-server/README.md

  dispatch-orchest-ami-build:
    needs: buildpush
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch
        run: >
          curl -X POST
          -u "${{secrets.PAT_USER}}:${{secrets.PAT_TOKEN}}"
          -H "Accept: application/vnd.github.v3+json"
          https://api.github.com/repos/orchest/cloud-infra/actions/workflows/build_amis.yml/dispatches
          -d '{"ref":"master"}'

  dispatch-version-update-info:
    needs: buildpush
    runs-on: ubuntu-latest

    steps:
      - name: Get latest version
        id: latest_version
        run: echo ::set-output name=LATEST_VERSION::${GITHUB_REF#refs/tags/}

      - name: Dispatch
        run: >
          curl -X POST
          -u "${{secrets.PAT_USER}}:${{secrets.PAT_TOKEN}}"
          -H "Accept: application/vnd.github.v3+json"
          https://api.github.com/repos/orchest/orchest-update-info/actions/workflows/update_latest_version.yml/dispatches
          -d "{\"ref\":\"master\", \"inputs\": {\"version\": \"$LATEST_VERSION\" }}"
        env:
          LATEST_VERSION: ${{ steps.latest_version.outputs.LATEST_VERSION}}
