# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
    branches: [ master ]

jobs:
  jupyter-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./orchest/jupyter-server/app

    - name: Create test environment
      run: |
        sudo mkdir /pipeline-dir

    - name: Test with pytest
      run: |
        python -m pytest -s
      working-directory: ./orchest/jupyter-server/app

  orchest-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./orchest/orchest-api/app

    - name: Test with pytest
      run: |
        python -m pytest -v
      working-directory: ./orchest/orchest-api/app

  memory-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./orchest/memory-server

    - name: Test with pytest
      run: |
        python -m pytest -v
      working-directory: ./orchest/memory-server
