# Runs all front-end/UI checks
name: UI

on:
  push:
    branches:
      - master
      - dev
      - "release/**"
    paths:
      - "**package.json"
      - "lib/design-system/**"
      - "lib/javascript/**"
      - "services/auth-server/**"
      - "services/orchest-webserver/**"
  pull_request:
    branches:
      - master
      - dev
      - "release/**"

jobs:
  pnpm-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      # Run our pnpm hook manually, with additional build checks
      - name: Setup pnpm
        run: npm run setup && pnpm install

      - name: Build pnpm packages
        run: pnpm run build

      - name: Lint pnpm packages
        run: pnpm run check
